/* Editorial Garden Modernism: reusable content map for the full Gillco Meraqui 50-page architecture. */
import { journalArticles, type JournalArticle } from './journalData';

export type PageConfig = { slug:string; title:string; eyebrow:string; intro:string; image?:string; sections:string[]; cta?:string; kind?:string; metaTitle?:string; metaDescription?:string; keywords?:string[]; journalArticle?:JournalArticle };

const S = {
  master:'/manus-storage/master-plan_64b1dacc.webp', arrival:'/manus-storage/meraqui-arrival_7a2cecde.webp', facade:'/manus-storage/clubhouse-facade_94904d49.webp', pool:'/manus-storage/meraqui-pool-courtyard_c9f3cb09.jpg', club:'/manus-storage/meraqui-clubhouse-evening_17dea46e.jpg', hero:'/manus-storage/meraqui-hero_69f6afeb.webp', video:'/manus-storage/gillcovideo_71045890.mp4', p3150:'/manus-storage/plan-3150_66bea140.webp', p3200:'/manus-storage/plan-3200_7016787a.webp', p3500:'/manus-storage/plan-3500_1ec533cb.webp', p4350:'/manus-storage/plan-4350_85e1cb37.webp', p4550:'/manus-storage/plan-4550_499b2df6.webp'
};
const page = (slug:string,title:string,eyebrow:string,intro:string,sections:string[],image?:string,kind?:string):PageConfig=>({slug,title,eyebrow,intro,sections,image,kind});

export const pages: PageConfig[] = [
page('gillco-meraqui-overview','Gillco Meraqui Project Overview','01 / PROJECT OVERVIEW','A complete view of the project: its location, scale, planning philosophy, residences, and the everyday experience being shaped at Sector 126, Mohali.',['Project snapshot','Design philosophy: dual-core living','Master plan at a glance','Who Gillco Meraqui is for'],S.master),
page('gillco-group-about','About Gillco Group — We Build Dreams','02 / THE BUILDER','Gillco Group has spent more than two decades turning land potential into considered residential and commercial environments across Punjab.',['Our founding story','Trust, discipline, value','25+ years of excellence','Residential and commercial legacy'],S.arrival),
page('gillco-group-projects',"Gillco Group's Portfolio of Trusted Developments",'03 / LEGACY PROJECTS','A portfolio perspective on the group behind Meraqui, and the design and execution values carried into this new address.',['Residential developments','Commercial developments','Why buyers choose Gillco','Meraqui: the next chapter'],S.facade),
page('gillco-meraqui-master-plan','Gillco Meraqui Master Layout Plan','04 / SITE PLANNING','Read the 12-acre master plan through its landscape, amenity, arrival, and residential zones.',['Site planning philosophy','Tower distribution across 12 acres','Green and recreational zoning','How to read the master plan'],S.master,'master'),
page('gillco-meraqui-floor-plans','Explore Every Gillco Meraqui Floor Plan','05 / FLOOR PLAN LIBRARY','Compare the five advertised residence sizes and request the complete plan set for a closer look.',['3+1 BHK floor plans','4 BHK floor plans','How to choose the right size','Request the complete floor plan set'],S.p3500,'plans'),
page('gillco-meraqui-3150-sqft-floor-plan','Gillco Meraqui — 3150 Sq.Ft. Floor Plan','06 / 3+1 BHK','A compact 3+1 BHK plan with room for flexible living, generous balconies, and a considered dual-core arrangement.',['Layout overview','Room-wise specifications','What is included','Compare with other sizes'],S.p3150,'plan'),
page('gillco-meraqui-3200-sqft-floor-plan','Gillco Meraqui — 3200 Sq.Ft. Floor Plan','07 / 3+1 BHK','The 3200 sq.ft. plan sits at the advertised entry point of the larger residence range, balancing everyday flow with private corners.',['Layout overview','Room-wise specifications','What is included','Compare with other sizes'],S.p3200,'plan'),
page('gillco-meraqui-3500-sqft-floor-plan','Gillco Meraqui — 3500 Sq.Ft. Floor Plan','08 / 3+1 BHK','A larger 3+1 BHK expression for families who want more room for guests, work, and unhurried weekends.',['Layout overview','Room-wise specifications','What is included','Compare with other sizes'],S.p3500,'plan'),
page('gillco-meraqui-4350-sqft-floor-plan','Gillco Meraqui — 4350 Sq.Ft. Floor Plan','09 / 4 BHK','An expansive 4 BHK plan shaped around privacy, family gathering, and a generous relationship with balconies and views.',['Layout overview','Room-wise specifications','What is included','Compare with other sizes'],S.p4350,'plan'),
page('gillco-meraqui-4550-sqft-floor-plan','Gillco Meraqui — 4550 Sq.Ft. Floor Plan','10 / 4 BHK','The most expansive advertised plan in the library, with space to shape the home around a larger family rhythm.',['Layout overview','Room-wise specifications','What is included','Compare with other sizes'],S.p4550,'plan'),
page('3-bhk-flats-gillco-meraqui','3+1 BHK Luxury Flats at Gillco Meraqui','11 / 3+1 BHK','A versatile additional room, generous living areas, premium in-home specifications, and the privacy of a dual-core plan.',['Why 3+1 BHK','Available sizes and floor plans','In-home features','Ideal for'],S.arrival),
page('4-bhk-flats-gillco-meraqui','4 BHK Luxury Flats at Gillco Meraqui','12 / 4 BHK','Large-format residences for families who value a clear separation between personal rooms, shared spaces, and everyday rituals.',['Why 4 BHK','Available sizes and floor plans','In-home features','Ideal for'],S.hero),
page('dual-core-flats-meaning-gillco-meraqui','What Makes a Flat “Dual-Core”?','13 / THE PLANNING IDEA','Dual-core planning is a simple idea with a meaningful effect: fewer residences per floor and a calmer relationship between private and shared life.',['The concept in plain language','Privacy by plan','How it changes the everyday','Explore the residences'],S.master),
page('gillco-meraqui-price','Gillco Meraqui Price & Cost Sheet','14 / TRANSPARENT PRICING','Pricing is available on request so that the residence, specification, and commercial terms can be discussed directly and responsibly.',['What the cost sheet includes','Residence sizes','Request current pricing','Important buyer notes'],S.club,'form'),
page('gillco-meraqui-payment-plan','Gillco Meraqui Payment Plan','15 / THE PURCHASE JOURNEY','Understand the conversation points that shape a purchase: reservation, construction-linked stages, documentation, and final handover.',['How payment conversations work','Milestone planning','Documentation','Speak with the team'],S.facade,'form'),
page('gillco-meraqui-amenities','World-Class Amenities at Gillco Meraqui','16 / THE AMENITY LANDSCAPE','A connected amenity story built around wellness, recreation, hospitality, and the small rituals that make a residence feel complete.',['Water and wellness','Clubhouse living','Sports and recreation','Greens for every age'],S.pool),
page('gillco-meraqui-clubhouse','The Elite Clubhouse at Gillco Meraqui','17 / CLUBHOUSE','A hospitality-minded clubhouse for slow mornings, family gatherings, conversations, and a more social way to live at home.',['Arrival and welcome','Gathering spaces','Everyday hospitality','A clubhouse with a point of view'],S.club),
page('gillco-meraqui-infinity-pool','The Infinity Pool at Gillco Meraqui','18 / WATER & WELLNESS','A long blue line through the landscape: a place for morning laps, easy afternoons, and a quieter relationship with the outdoors.',['The pool experience','Wellness without performance','Landscape and shade','A day by the water'],S.pool),
page('gillco-meraqui-private-theatre','Mini Private Theatre at Gillco Meraqui','19 / LEISURE','A compact theatre experience for film nights, family rituals, and the pleasure of staying in.',['A room for stories','Family movie nights','An intimate amenity','Explore the clubhouse'],S.club),
page('gillco-meraqui-sports-court','Multi Sports Court & Athletic Facilities','20 / SPORTS & RECREATION','Active spaces that make movement easy to begin, whether the day calls for a match, a run, or a few minutes outdoors.',['Court and play surfaces','Movement for all ages','A healthier daily rhythm','Explore the amenity plan'],S.arrival),
page('gillco-meraqui-jogging-track-landscaped-greens','Landscaped Greens & Jogging Track at Gillco Meraqui','21 / LANDSCAPE','Landscape is not a border at Meraqui. It is the route between home, amenity, and the slower moments in between.',['The landscape framework','Jogging and walking','Garden rooms','A greener everyday'],S.pool),
page('gillco-meraqui-kids-play-area',"Kids' Play Area & Family Amenities",'22 / FAMILY LIVING','A family-friendly amenity layer with space for play, pause, and the kind of outdoor independence children remember.',['Designed for different ages','Play and supervision','Family time outdoors','A place to grow into'],S.arrival),
page('smart-home-automation-flats-mohali','Smart Home Automation at Gillco Meraqui','23 / IN-HOME TECHNOLOGY','Technology is most useful when it feels natural: supporting comfort, convenience, and the way each household already lives.',['What home automation can support','Comfort and convenience','A future-ready home','Request specifications'],S.facade),
page('gillco-meraqui-double-height-lobby','A Grand Double-Height Entrance Lobby','24 / ARRIVAL','The first threshold sets the tone: a generous, double-height arrival designed to feel composed, bright, and unmistakably residential.',['The arrival sequence','Material and light','A memorable first impression','From lobby to home'],S.facade),
page('gillco-meraqui-location','Gillco Meraqui Location & Connectivity','25 / THE ADDRESS','On Airport Road in Sector 126, Meraqui places home within reach of Chandigarh, the airport corridor, and Mohali’s expanding everyday ecosystem.',['The location at a glance','Airport Road access','The 15-minute radius','Explore the neighbourhood'],S.master,'location'),
page('airport-road-mohali-connectivity','Why Airport Road, Mohali Is a Connectivity Hub','26 / CONNECTIVITY','Airport Road is becoming one of the region’s most legible urban connectors, linking residential life to the city, the airport, and the wider tricity.',['A strategic road address','City and airport connections','The corridor effect','A better daily commute'],S.hero),
page('sector-126-mohali-guide','Living in Sector 126, Mohali','27 / THE NEIGHBOURHOOD','A guide to the evolving residential character of Sector 126 and the everyday conveniences that shape life around it.',['The character of Sector 126','Everyday essentials','Green and open context','A neighbourhood in motion'],S.arrival),
page('gillco-meraqui-distance-from-chandigarh','How Close Is Gillco Meraqui to Chandigarh?','28 / TRICITY ACCESS','Meraqui is positioned for people whose life moves between Mohali, Chandigarh, the airport corridor, and the wider tricity.',['The Chandigarh connection','Road access','Work, culture, and leisure','Plan your route'],S.hero),
page('flats-near-mohali-international-airport','Flats Near Mohali International Airport','29 / AIRPORT CORRIDOR','For frequent travellers and connected professionals, the airport corridor offers a practical relationship between home and movement.',['Airport access','A connected residential choice','Travel and everyday life','Explore the address'],S.arrival),
page('gillco-meraqui-nearby-schools-hospitals','Schools & Hospitals Near Gillco Meraqui','30 / ESSENTIALS','A home becomes more useful when the everyday essentials are within a reasonable reach. Explore the wider education and healthcare context around the address.',['Education context','Healthcare context','Planning the family day','Verify the latest distances'],S.master),
page('flats-near-pca-stadium-mohali','Flats Near PCA Stadium, Mohali','31 / LIFESTYLE ACCESS','A location close to the stadium, leisure, and the city’s social rhythm gives weekends and spontaneous plans a little more room.',['The stadium connection','Leisure and social life','A location with energy','Discover Meraqui'],S.hero),
page('gillco-meraqui-investment-benefits','Why Invest in Gillco Meraqui','32 / BUYER PERSPECTIVE','A responsible investment conversation begins with the project, the address, the developer, the specification, and the buyer’s own horizon.',['The address thesis','Product and planning','Builder confidence','Do your own due diligence'],S.facade,'form'),
page('rental-appreciation-sector-126-mohali','Rental & Appreciation Outlook in Sector 126, Mohali','33 / MARKET CONTEXT','Consider the rental and appreciation conversation through location quality, demand drivers, delivery, and verified market information rather than promises.',['What can influence rental demand','What can influence appreciation','Questions for buyers','A transparent next step'],S.hero,'form'),
page('luxury-apartments-airport-road-mohali','Luxury Apartments on Airport Road, Mohali','34 / CATEGORY GUIDE','A category-level guide to what makes a premium apartment on Airport Road feel different: planning, landscape, amenities, and access.',['What luxury means here','A better plan','Amenity as daily value','Compare residence sizes'],S.arrival),
page('new-launch-residential-projects-mohali','New Launch Residential Projects in Mohali','35 / MARKET GUIDE','A practical framework for comparing a new residential launch in Mohali, from approvals and plans to execution, specifications, and the true cost of ownership.',['How to compare launches','Questions to ask','Where Meraqui fits','Request the project pack'],S.master),
page('gillco-meraqui-vs-luxury-projects-mohali',"How Gillco Meraqui Compares in Mohali's Luxury Market",'36 / COMPARISON','Compare on the things that stay meaningful after the launch moment: plan quality, privacy, landscape, amenity depth, location, and transparency.',['Planning and privacy','Scale and landscape','Location and access','Make an informed comparison'],S.hero),
page('gillco-meraqui-rera-approved','Gillco Meraqui Is RERA Approved','37 / RERA & TRANSPARENCY','The project is presented with the RERA registration reference PBRERA-SAS81-PR1390-062026 so buyers can make a more informed enquiry.',['RERA at a glance','What buyers should verify','Project information','Ask for the documentation'],S.master,'rera'),
page('gillco-meraqui-specifications','Gillco Meraqui — Project Specifications','38 / THE DETAIL','Review the planning, residential, amenity, and in-home specification story behind Gillco Meraqui.',['Project scale','Residence configurations','In-home features','Amenity and landscape framework'],S.facade),
page('gillco-meraqui-gallery','Gillco Meraqui — Project Gallery','39 / VISUAL ARCHIVE','A visual archive of the architecture, arrival, landscape, amenity spaces, and plan documents that shape the Meraqui story.',['Architecture','Landscape and amenity','Master plan','Floor plan library'],S.hero,'gallery'),
page('gillco-meraqui-video-walkthrough','Watch the Gillco Meraqui Video Walkthrough','40 / THE FILM','Use the supplied project film to understand the architectural language, arrival experience, and intended atmosphere of Gillco Meraqui.',['Watch the walkthrough','What to look for','Continue exploring','Book a private visit'],S.video,'video'),
page('gillco-meraqui-virtual-tour','Take a Virtual Tour of Gillco Meraqui','41 / DIGITAL EXPERIENCE','A virtual-tour style overview of the project’s arrival, architecture, landscape, and residence planning.',['Arrive at Meraqui','Move through the landscape','Explore a residence','Request a guided walkthrough'],S.hero),
page('gillco-meraqui-brochure','Download the Gillco Meraqui Brochure','42 / PROJECT PACK','Request the detailed brochure and receive the project story, floor plans, specifications, and buyer information in one considered pack.',['What the brochure includes','Floor plan set','Specifications and approvals','Request the brochure'],S.club,'form'),
page('gillco-meraqui-book-site-visit','Book a Site Visit to Gillco Meraqui','43 / PRIVATE APPOINTMENTS','See the address, understand the scale, and ask the questions that matter in a private conversation with the team.',['What to expect','Before you visit','Choose a preferred time','Confirm your appointment'],S.arrival,'form'),
page('gillco-meraqui-pre-register','Pre-Register for Gillco Meraqui','44 / EARLY ACCESS','Register your interest to receive project updates and an early conversation about availability, plans, and next steps.',['What pre-registration means','The information we need','Stay informed','Register your interest'],S.hero,'form'),
page('contact-gillco-meraqui','Contact Gillco Meraqui','45 / START A CONVERSATION','Speak with the Gillco Meraqui team about plans, pricing, specifications, availability, or a private site visit.',['Call the team','Request a callback','Visit the project','Send an enquiry'],S.facade,'form'),
page('gillco-meraqui-faq','Gillco Meraqui — Frequently Asked Questions','46 / QUESTIONS, ANSWERED','A clear starting point for the questions buyers commonly ask about the project, plans, approvals, location, pricing, and the purchase journey.',['Project and location','Plans and specifications','Pricing and payment','Approvals and process'],S.master,'faq'),
page('blog/airport-road-mohali-real-estate-hotspot','Why Airport Road, Mohali Is Emerging as a Real Estate Hotspot','47 / JOURNAL','Airport Road is becoming a more important residential corridor because it connects movement, employment, city access, and a new generation of planned communities.',['The corridor story','Why connectivity compounds','What buyers should assess','Meraqui in context'],S.hero,'blog'),
page('blog/gillco-group-25-years-legacy','Gillco Group: 25 Years of Building Trust in North India','48 / JOURNAL','A closer look at the values, continuity, and execution mindset behind Gillco Group’s long residential and commercial journey.',['A founding vision','Trust built over time','What continuity means for buyers','The Meraqui chapter'],S.arrival,'blog'),
page('thank-you',"Thank You — We've Received Your Enquiry",'49 / NEXT STEP','Your enquiry has reached the Gillco Meraqui team. Keep the project pack close and expect a response from the team shortly.',['Your enquiry is in','What happens next','Keep exploring Meraqui','Return to the homepage'],S.club,'thankyou'),
  page(
  'gillco-meraqui-parking',
  'Gillco Meraqui Parking Facilities',
  '75 / PARKING',
  'Explore parking facilities at Gillco Meraqui, including resident parking, visitor parking, accessibility, security, and EV charging considerations.',
  [
    'Parking Facilities at Gillco Meraqui',
    'Resident Parking',
    'Visitor Parking',
    'Parking Convenience & Accessibility',
    'Security & Parking Management',
    'EV Charging Readiness',
    'Why Parking Matters When Buying at Gillco Meraqui'
  ],
  S.facade
)
];

export const pageBySlug = Object.fromEntries(pages.map(p=>[p.slug,p])) as Record<string,PageConfig>;

export const expansionPages: PageConfig[] = [
page('gillco-meraqui-plc','Gillco Meraqui PLC Guide','50 / COST CLARITY','This guide explains how preferential location charges may apply to a residential booking and what a buyer should request in writing before making a decision.',['What are preferential location charges?','How PLC can affect a cost sheet','Questions to ask before booking','Request the current commercial sheet'],S.master,'form'),
page('gillco-meraqui-possession-timeline','Gillco Meraqui Possession & Project Timeline','51 / DELIVERY','Gillco Meraqui is presented with a 2030 possession target. Buyers should verify the latest schedule, approvals, and construction milestones directly with the official project team.',['What the current timeline indicates','How to read a construction schedule','Documents buyers should request','Stay updated on delivery'],S.arrival),
page('emi-calculator-mohali','EMI Calculator for Mohali Luxury Flats','52 / HOME-LOAN PLANNING','Use this educational EMI calculator to explore how loan amount, tenure, and an assumed interest rate affect an estimated monthly repayment. It is not a loan offer or financial advice.',['Estimate a monthly repayment','How loan tenure changes the estimate','What to discuss with a lender','Plan a responsible budget'],S.facade,'emi'),
page('nri-investment-mohali','NRI Investment Guide for Mohali Real Estate','53 / NRI BUYER GUIDE','NRI buyers can use this neutral guide to frame questions about verification, documentation, remote coordination, and independent professional advice before considering a Mohali property purchase.',['Start with independent verification','Understand the booking process','Coordinate from overseas','Seek professional advice'],S.hero),
page('gillco-meraqui-reviews','Gillco Meraqui Reviews & Buyer Information','54 / BUYER INFORMATION','Gillco Meraqui does not publish unverified customer reviews. This page explains the information and verification steps a prospective buyer can use before deciding whether to enquire.',['Why verified feedback matters','Questions to ask the sales team','How to compare project information','Share verified documentation'],S.club,'reviews'),
page('gillco-meraqui-awards-media','Gillco Meraqui Awards & Media','55 / PROJECT UPDATES','Official awards, media mentions, and announcements should be reviewed from primary sources. This page will publish only documented project and developer updates.',['Official project updates','Media and awards policy','How to verify a claim','Stay informed'],S.arrival,'updates'),
page('gillco-meraqui-gymnasium','Gymnasium at Gillco Meraqui','56 / FITNESS','Explore the intended fitness amenity experience at Gillco Meraqui and request the final amenity specification from the sales team before relying on any feature list.',['Fitness in the daily routine','Amenity specification questions','A balanced lifestyle plan','Explore the full amenity set'],S.pool),
page('gillco-meraqui-senior-citizen-zone','Senior Citizen Zone at Gillco Meraqui','57 / EVERY GENERATION','A considerate community gives different generations a place to pause, meet, and enjoy the landscape. Confirm final amenity details with the project team.',['A calmer shared setting','Family-friendly planning','Questions to verify','Explore landscaped greens'],S.pool),
page('sector-126-mohali-area-guide','Sector 126 Mohali Area Guide','58 / AREA GUIDE','Sector 126 sits within Mohali’s Airport Road context. This practical area guide helps buyers frame questions around mobility, everyday services, and the wider neighbourhood before they visit.',['What defines the area','Everyday services to verify','Mobility and road access','Plan a local visit'],S.master,'guide'),
page('airport-road-connectivity-infrastructure','Airport Road Mohali Connectivity & Infrastructure','59 / INFRASTRUCTURE','Airport Road is a key residential corridor in the Mohali context. Verify current road works, travel times, and public-transport information from official sources before relying on a route plan.',['Understanding the corridor','Airport and city access','Infrastructure questions to ask','Visit the project area'],S.hero,'guide'),
page('nearby-landmarks-gillco-meraqui','Nearby Landmarks to Gillco Meraqui','60 / LOCAL CONTEXT','Use this planning page to organise a site visit around schools, hospitals, commercial areas, and other places that matter to your household. Confirm every distance and operating detail independently.',['Education and healthcare context','Everyday shopping and services','Plan a local route','Request a guided visit'],S.master,'guide'),
page('gillco-group-story','Gillco Group Story & Timeline','61 / OUR STORY','Gillco Group’s story is rooted in a long-term approach to building residential and commercial environments in Punjab. Request official company materials for the latest verified timeline.',['A long-term development view','The group timeline','Values behind the work','Explore Gillco projects'],S.arrival),
page('gillco-group-ongoing-projects','Gillco Group Ongoing Projects','62 / DEVELOPMENT PIPELINE','Explore Gillco Group’s project context through official updates and published project information. Availability, status, and specifications should always be confirmed with the relevant project team.',['How to review ongoing work','Ask for official updates','Compare project information','Contact Gillco Group'],S.facade),
page('gillco-group-leadership','Gillco Group Leadership Team','63 / LEADERSHIP','Leadership information should be drawn from approved company sources. This page provides a place for officially confirmed management profiles and updates.',['Leadership and accountability','What to verify','Official company information','Contact the team'],S.club,'updates'),
page('gillco-group-community','Gillco Group Community Initiatives','64 / COMMUNITY','Gillco Group will publish community initiatives and related documentation here when approved source materials are available. No unverified CSR claims are presented.',['Community approach','Documentation matters','Future updates','Stay connected'],S.pool,'updates'),
page('privacy-policy','Gillco Meraqui Privacy Policy','65 / PRIVACY','This privacy policy explains how an enquiry website may collect and use submitted contact information. Review the final approved policy before relying on it.',['Information collected','How enquiry details may be used','Your choices','Contact for privacy questions'],S.facade,'legal'),
page('terms-and-conditions','Gillco Meraqui Terms & Conditions','66 / TERMS','These website terms outline general use of the Gillco Meraqui website. Commercial terms, availability, and project information remain subject to official documentation and confirmation.',['Using this website','Project-information limitations','Intellectual property','Questions about terms'],S.facade,'legal'),
page('rera-disclaimer','Gillco Meraqui RERA Disclaimer','67 / RERA DISCLAIMER','Gillco Meraqui is presented with RERA registration PBRERA-SAS81-PR1390-062026. Buyers should verify all current information with the official RERA portal and project documentation.',['RERA reference','Buyer verification steps','Advertising and information','Official documents'],S.master,'legal'),
page('sitemap','Gillco Meraqui HTML Sitemap','68 / ALL PAGES','Use this sitemap to navigate project information, residence guides, buyer resources, Gillco Group information, and journal articles from one organised place.',['Project information','Buyer resources','Gillco Group','Journal and utilities'],S.master,'sitemap'),
page('journal','Gillco Meraqui Journal','69 / JOURNAL','The Gillco Meraqui Journal provides neutral, topic-focused guides for buyers researching Mohali, Airport Road, RERA, layouts, budgeting, and the airport corridor.',['Area and market guides','Homebuyer education','Layout comparisons','Browse all articles'],S.hero,'journal'),
page('blog/sector-126-mohali-real-estate-hub',"Sector 126 Mohali: Airport Road's Next Real Estate Hub",'70 / JOURNAL','Sector 126 is increasingly discussed within Mohali’s Airport Road context. This guide explains the questions buyers should ask about services, travel patterns, road access, and the character of a developing residential area.',['Why the area draws attention','How to assess local growth','Questions for a site visit','Meraqui in context'],S.hero,'blog'),
page('blog/3-plus-1-bhk-vs-4-bhk','3+1 BHK vs 4 BHK: Which Layout Fits Your Family?','71 / JOURNAL','The right layout depends on household size, work patterns, privacy needs, and the way shared areas are actually used. This guide compares 3+1 BHK and 4 BHK choices without prescribing one answer.',['Start with daily routines','Comparing room flexibility','Consider future needs','Review the floor plans'],S.p3500,'blog'),
page('blog/rera-in-punjab-homebuyer-guide','RERA in Punjab Explained for Mohali Homebuyers','72 / JOURNAL','RERA verification is an important part of a property enquiry. This guide explains the kinds of details a buyer should check in project documentation and on official portals before booking.',['What RERA is designed to do','What to verify','Keep a document trail','Use independent advice'],S.master,'blog'),
page('blog/home-loan-payment-plan-guide','Home Loan & Payment Plan Guide for Mohali Buyers','73 / JOURNAL','A home loan and payment plan should be understood through your own budget, lender terms, loan eligibility, and professional advice. This guide provides an educational framework rather than a lending recommendation.',['Start with affordability','Understand the loan process','Read payment milestones','Use the EMI calculator'],S.facade,'blog'),
page('blog/living-near-chandigarh-airport','Living Near Chandigarh Airport: A Mohali Guide','74 / JOURNAL','Living near the Chandigarh airport corridor can change how a household thinks about work, travel, services, and weekend plans. This guide helps prospective buyers frame a location visit.',['The airport-corridor lifestyle','Travel-time questions','Services and routines','Explore the location'],S.hero,'blog')
];

export const journalPages: PageConfig[] = journalArticles.map((article, index) => ({
  slug: article.slug,
  title: article.h1,
  eyebrow: `JOURNAL / ${String(index + 1).padStart(2, '0')}`,
  intro: article.metaDescription,
  image: article.cover,
  sections: article.outline.filter(item => item.level === 2).map(item => item.heading),
  cta: article.cta,
  kind: 'journalArticle',
  metaTitle: article.metaTitle,
  metaDescription: article.metaDescription,
  keywords: article.keywords,
  journalArticle: article,
}));

export const allPages = [...pages, ...expansionPages, ...journalPages];
