/* Editorial Garden Modernism: practical, transparent conversion and education blocks for the expanded Meraqui content ecosystem. */
import { useMemo, useState } from 'react';
import { Calculator, CheckCircle2, Copy, Facebook, Linkedin, MessageCircle, Phone, Share2 } from 'lucide-react';
import { Link } from 'wouter';
import type { PageConfig } from '@/lib/siteData';
import { allPages } from '@/lib/siteData';
import { WhatsAppIcon } from '@/components/BrandIcons';

const FAQ_BASE = [
  ['What should I verify before relying on project information?', 'Request the latest official project documentation, confirm current availability and specifications with the authorised team, and independently verify information that affects your decision.'],
  ['How can I arrange a site visit or receive details?', 'You can call the sales team, use WhatsApp, or submit the enquiry form. A private appointment can then be arranged around your preferred time.'],
  ['Where can I find related Gillco Meraqui information?', 'Use the linked floor plans, location guides, RERA material, amenities pages, and buyer resources to build a fuller understanding before you enquire.']
];

export function PageFAQ({ page }: { page: PageConfig }) {
  const faqs = useMemo(() => [
    [`What is ${page.title}?`, `${page.intro} For the latest official detail, availability, and documentation, contact the project team directly.`],
    [`What should I ask about ${page.sections[0]?.toLowerCase() || 'this topic'}?`, `Ask for current written information, the final project specification where relevant, and the documentation that explains the point in the context of your own requirements.`],
    [`How can I verify ${page.sections[1]?.toLowerCase() || 'the details'}?`, `Use official project documents, request the latest approved information from the authorised team, and seek independent advice where a detail may affect a financial or legal decision.`],
    [`What is the next step after reading about ${page.sections[2]?.toLowerCase() || 'Gillco Meraqui'}?`, `Compare the linked project pages, note any questions you still have, and arrange a private call, WhatsApp conversation, or site visit with the project team.`]
  ], [page]);
  return <section className="page-faq" aria-label={`${page.title} frequently asked questions`}><p className="eyebrow">Questions, answered</p><h2>What else should you <i>know?</i></h2>{faqs.map(([question,answer], index)=><details key={question} open={index===0}><summary><span>0{index+1}</span>{question}</summary><p>{answer}</p></details>)}</section>;
}

export function EMICalculator(){
  const [loan,setLoan] = useState(10000000); const [rate,setRate] = useState(8.5); const [years,setYears] = useState(20);
  const monthly = useMemo(()=>{ const r=rate/1200; const n=years*12; return r === 0 ? loan/n : (loan*r*Math.pow(1+r,n))/(Math.pow(1+r,n)-1); },[loan,rate,years]);
  return <section className="emi-card"><div><p className="eyebrow">Educational planning tool</p><h2>Estimate an <i>EMI.</i></h2><p>This illustration is not a loan offer, financial advice, or an indication of eligibility. Actual lender rates, terms, taxes, and charges can differ.</p></div><div className="emi-form"><label>Estimated loan amount <strong>₹{(loan/100000).toFixed(0)} lakh</strong><input type="range" min="2000000" max="50000000" step="500000" value={loan} onChange={e=>setLoan(Number(e.target.value))}/></label><label>Assumed annual interest rate <strong>{rate.toFixed(1)}%</strong><input type="range" min="6" max="15" step="0.1" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>Loan tenure <strong>{years} years</strong><input type="range" min="5" max="30" step="1" value={years} onChange={e=>setYears(Number(e.target.value))}/></label><div className="emi-result"><span>Estimated monthly EMI</span><strong>₹{Math.round(monthly).toLocaleString('en-IN')}</strong><small>Based solely on the inputs above.</small></div></div></section>;
}

export function BlogShare({ title }: { title:string }){ const copy = async()=>{ await navigator.clipboard?.writeText(window.location.href); alert('Link copied. You can now share it on Instagram or any preferred channel.');}; const url=typeof window==='undefined'?'':window.location.href; return <div className="share-bar"><span><Share2 size={15}/> Share this guide</span><a href={`https://wa.me/?text=${encodeURIComponent(`${title} ${url}`)}`} target="_blank" rel="noreferrer" aria-label="Share on WhatsApp"><MessageCircle size={16}/></a><a href={`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer" aria-label="Share on Facebook"><Facebook size={16}/></a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(url)}`} target="_blank" rel="noreferrer" aria-label="Share on LinkedIn"><Linkedin size={16}/></a><button onClick={copy} aria-label="Copy link for Instagram"><Copy size={16}/></button></div>}

export function ContactInformation(){ return <section className="contact-information"><p className="eyebrow">Speak to the project team</p><h2>Contact <i>Gillco Meraqui.</i></h2><div className="contact-information-grid"><div><span>Sales — primary</span><a href="tel:+919779799705">+91 97797 99705</a><a className="whatsapp-inline" href="https://wa.me/919779799705" target="_blank" rel="noreferrer"><MessageCircle size={15}/> WhatsApp this number</a></div><div><span>Sales — secondary</span><a href="tel:+919596365534">+91 95963 65534</a><p>Project area: Sector 126, Airport Road, Mohali, Punjab. The exact site address, sales-office address, email, hours, and map pin are awaiting confirmation.</p></div></div><iframe className="contact-map" title="Sector 126 Airport Road Mohali project area" src="https://www.google.com/maps?q=Sector%20126%20Airport%20Road%20Mohali&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Sector+126+Airport+Road+Mohali" target="_blank" rel="noreferrer">Open the Sector 126 project area in Google Maps</a></section> }

export function JournalListing(){ const articles=allPages.filter(p=>p.kind==='blog'||p.kind==='journalArticle'); return <section className="journal-listing"><p className="eyebrow">Buyer education</p><h2>Read the <i>journal.</i></h2><div>{articles.map(article=><Link className="journal-card" href={`/${article.slug}`} key={article.slug}><img src={article.image} alt={article.journalArticle?.alt || `${article.title} cover`} /><span>{article.journalArticle?.primaryKeyword || 'Journal'}</span><h3>{article.title}</h3><p>{article.intro.slice(0,120)}…</p></Link>)}</div></section> }

export function BlogLongform({ page }: { page: PageConfig }){ const sections=page.sections.slice(0,4); return <section className="blog-longform"><p className="eyebrow">A considered guide</p><h2>A closer <i>read.</i></h2>{sections.map((section,index)=><article key={section}><h3>{section}</h3><p>{`When researching ${page.title.toLowerCase()}, it helps to separate a useful detail from a broad promise. ${section} is best considered through the needs of a real household: daily movement, work and school patterns, privacy, budget, travel, and the services that make a location or residence function over time. Rather than relying on one claim, gather current project information, compare official documents, and record the questions that matter to you before you visit.`}</p><p>{`A practical next step is to test the topic during a site visit or a conversation with the relevant team. Ask what is confirmed today, what remains subject to approval, and which supporting document explains the point. This approach makes ${section.toLowerCase()} easier to evaluate calmly, particularly when property information is presented alongside lifestyle imagery or high-level marketing language. Independent advice is appropriate whenever a detail could affect a booking, payment, or longer-term financial decision.`}</p>{index===1&&<ol><li>List the information you need to verify.</li><li>Request the latest official material in writing.</li><li>Compare it with your household’s priorities.</li><li>Take time to decide before committing.</li></ol>}</article>)}</section> }

export function SitemapListing(){ const groups=[['Project',allPages.filter(p=>!p.slug.startsWith('blog/') && p.kind!=='journalArticle' && !['gillco-group-about','gillco-group-projects','gillco-group-story','gillco-group-ongoing-projects','gillco-group-leadership','gillco-group-community','privacy-policy','terms-and-conditions','rera-disclaimer','sitemap','journal'].includes(p.slug))],['Gillco Group',allPages.filter(p=>p.slug.startsWith('gillco-group'))],['Journal',allPages.filter(p=>p.kind==='blog'||p.kind==='journalArticle')],['Utilities',allPages.filter(p=>['privacy-policy','terms-and-conditions','rera-disclaimer','sitemap','journal'].includes(p.slug))]]; return <section className="html-sitemap">{groups.map(([label,list])=><div key={label as string}><p className="eyebrow">{label as string}</p>{(list as PageConfig[]).map(p=><Link key={p.slug} href={`/${p.slug}`}>{p.title}</Link>)}</div>)}</section> }

export function RelatedLinks({ page }: { page: PageConfig }){ const pool=page.kind==='journalArticle'?allPages.filter(p=>p.kind==='journalArticle'&&p.slug!==page.slug):allPages.filter(p=>p.kind!== 'legal'&&p.kind!=='journalArticle'&&p.slug!==page.slug); const candidates=pool.slice(0,3); return <aside className="related-links"><p className="eyebrow">Continue exploring</p>{candidates.map(p=><Link href={`/${p.slug}`} key={p.slug}>{p.title}<span>↗</span></Link>)}</aside> }

export function ContactDock(){ return <><a className="whatsapp-float" href="https://wa.me/919779799705" target="_blank" rel="noreferrer" aria-label="Chat on WhatsApp"><WhatsAppIcon size={22}/><span>WhatsApp</span></a><div className="mobile-contact-dock"><a href="tel:+919779799705"><Phone size={15}/> Call</a><a href="https://wa.me/919779799705" target="_blank" rel="noreferrer"><WhatsAppIcon size={16}/> WhatsApp</a></div></> }
