/* Editorial Garden Modernism: final shared conversion and credibility chrome for the publish-ready site. */
import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, Check, MessageCircle, Phone, X } from 'lucide-react';
import { Link } from 'wouter';
import { trpc } from '@/lib/trpc';
import { WhatsAppIcon } from '@/components/BrandIcons';

const logo = '/manus-storage/gillco-logo-original_0766c458.png';

export function SiteFooter(){ const year=new Date().getFullYear(); return <footer className="final-footer"><div className="footer-top"><div className="footer-about"><img src={logo} alt="Gillco Group"/><p>Gillco Meraqui is a luxury residential project in Sector 126, Airport Road, Mohali, designed around privacy, landscape, and generous family living.</p><div className="footer-social-note">Official social profiles will be added when supplied.</div></div><div><h3>Quick links</h3><Link href="/">Home</Link><Link href="/gillco-group-about">About Gillco Group</Link><Link href="/contact-gillco-meraqui">Contact now</Link><Link href="/gillco-meraqui-book-site-visit">Book a site visit</Link><Link href="/gillco-meraqui-faq">FAQ</Link><Link href="/gillco-meraqui-gallery">Gallery</Link></div><div><h3>Project</h3><Link href="/gillco-meraqui-floor-plans">Floor plans</Link><Link href="/gillco-meraqui-amenities">Amenities</Link><Link href="/gillco-meraqui-price">Price & cost sheet</Link><Link href="/gillco-meraqui-location">Location</Link><Link href="/gillco-meraqui-rera-approved">RERA approval</Link></div><div><h3>Legal / utility</h3><Link href="/privacy-policy">Privacy policy</Link><Link href="/terms-and-conditions">Terms & conditions</Link><Link href="/rera-disclaimer">RERA disclaimer</Link><Link href="/sitemap">Sitemap</Link></div></div><div className="footer-bottom"><span>© {year} Gillco Meraqui. All rights reserved.</span><span>RERA: PBRERA-SAS81-PR1390-062026</span><span><a href="tel:+919779799705">+91 97797 99705</a> · <a href="tel:+919596365534">+91 95963 65534</a></span><a className="aimarketians-credit" href="https://www.aimarketians.com" target="_blank" rel="noreferrer">Developed & Designed by AiMarketians <ArrowUpRight size={13}/></a></div></footer> }

const timings=[15000,25000,40000];
export function LeadPopup(){
  const [open,setOpen]=useState(false); const [dismissals,setDismissals]=useState(0); const [name,setName]=useState(''); const [phone,setPhone]=useState(''); const [configuration,setConfiguration]=useState<'3 BHK'|'4 BHK'>('3 BHK'); const [budget,setBudget]=useState<'₹1 Cr'|'₹2 Cr'|'₹3 Cr'|'₹4 Cr+'>('₹1 Cr'); const capture=trpc.lead.capture.useMutation();
  useEffect(()=>{ const submitted=sessionStorage.getItem('gillcoLeadSubmitted')==='true'; const closed=Number(sessionStorage.getItem('gillcoLeadDismissals')||'0'); const next=Number(sessionStorage.getItem('gillcoLeadNextAt')||'0'); setDismissals(closed); if(submitted||closed>=4)return; const wait=next>0?Math.max(next-Date.now(),0):5000; const timer=window.setTimeout(()=>setOpen(true),wait); return()=>window.clearTimeout(timer); },[]);
  const dismiss=()=>{ const next=dismissals+1; setDismissals(next); sessionStorage.setItem('gillcoLeadDismissals',String(next)); setOpen(false); if(next<4){ const at=Date.now()+(timings[next-1]||40000); sessionStorage.setItem('gillcoLeadNextAt',String(at)); window.setTimeout(()=>setOpen(true),timings[next-1]||40000); } else sessionStorage.removeItem('gillcoLeadNextAt'); };
  const submit=async(e:React.FormEvent)=>{ e.preventDefault(); if(!name.trim()||!phone.trim()) return; const message=`New Gillco Meraqui lead%0AName: ${encodeURIComponent(name.trim())}%0APhone: ${encodeURIComponent(phone.trim())}%0AConfiguration: ${encodeURIComponent(configuration)}%0ABudget: ${encodeURIComponent(budget)}`; try{ await capture.mutateAsync({name:name.trim(),phone:phone.trim(),configuration,budget,source:'timed-popup'}); } finally { sessionStorage.setItem('gillcoLeadSubmitted','true'); sessionStorage.removeItem('gillcoLeadNextAt'); setOpen(false); window.open(`https://wa.me/919779799705?text=${message}`,'_blank','noopener,noreferrer'); } };
  if(!open)return null; return <div className="lead-popup-backdrop" role="dialog" aria-modal="true" aria-label="Gillco Meraqui enquiry"><form className="lead-popup" onSubmit={submit}><button className="lead-close" type="button" onClick={dismiss} aria-label="Close lead form"><X size={18}/></button><img src={logo} alt="Gillco Group"/><p className="eyebrow">Private project access</p><h2>Find your <i>right fit.</i></h2><p>Tell us what you are looking for and continue the conversation directly on WhatsApp.</p><label>Name<input value={name} onChange={e=>setName(e.target.value)} required placeholder="Your name"/></label><label>Phone number<input value={phone} onChange={e=>setPhone(e.target.value.replace(/[^0-9+()\-\s]/g,''))} required inputMode="tel" placeholder="+91"/></label><fieldset><legend>Configuration type</legend><div className="choice-row">{(['3 BHK','4 BHK'] as const).map(v=><button type="button" onClick={()=>setConfiguration(v)} className={configuration===v?'chosen':''} key={v}>{v}</button>)}</div></fieldset><fieldset><legend>Budget</legend><div className="choice-row budget-row">{(['₹1 Cr','₹2 Cr','₹3 Cr','₹4 Cr+'] as const).map(v=><button type="button" onClick={()=>setBudget(v)} className={budget===v?'chosen':''} key={v}>{v}</button>)}</div></fieldset><button className="button button-brass" disabled={capture.isPending} type="submit">{capture.isPending?'Saving your enquiry…':'Continue on WhatsApp'} <WhatsAppIcon size={16}/></button><small>By continuing, you agree to be contacted about Gillco Meraqui.</small></form></div>;
}
